DROP TABLE IF EXISTS `exams`;
DROP TABLE IF EXISTS `exam_questions`;
DROP TABLE IF EXISTS `accounts`;
DROP TABLE IF EXISTS `answers`;
DROP TABLE IF EXISTS `media`;
DROP TABLE IF EXISTS `questions`;
DROP TABLE IF EXISTS `themes`;
DROP TABLE IF EXISTS `subjects`;

CREATE TABLE `accounts` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL UNIQUE,
  `passwordhash` VARCHAR(150) NOT NULL,
  `roles` SET('none', 'admin', 'student', 'teacher') NOT NULL DEFAULT 'none'
);


CREATE TABLE `subjects` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` varchar(50) NOT NULL UNIQUE
);


CREATE TABLE `themes` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` varchar(50) NOT NULL UNIQUE,
  `subjectid` INT UNSIGNED NOT NULL,
  FOREIGN KEY (subjectid)
    REFERENCES subjects (id)
    ON DELETE CASCADE
);


CREATE TABLE `questions` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `points` INT UNSIGNED NOT NULL,
  `subjectid` INT UNSIGNED NOT NULL,
  `themeid` INT UNSIGNED NOT NULL,
  FOREIGN KEY (subjectid)
    REFERENCES subjects (id)
    ON DELETE CASCADE,
  FOREIGN KEY (themeid)
    REFERENCES themes (id)
    ON DELETE CASCADE
);


CREATE TABLE `answers` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `text` VARCHAR(150) NOT NULL,
  `correct` BOOLEAN NOT NULL,
  `questionid` INT UNSIGNED NOT NULL,
  FOREIGN KEY (questionid)
    REFERENCES questions (id)
    ON DELETE CASCADE
);


CREATE TABLE `media` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `content` MEDIUMBLOB NOT NULL,
  `questionid` INT UNSIGNED NOT NULL,
  FOREIGN KEY (questionid)
    REFERENCES questions (id)
    ON DELETE CASCADE
);


CREATE TABLE `exams` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `startdate` DATETIME NOT NULL,
  `enddate` DATETIME NOT NULL,
  `timetosolve` TIME NOT NULL,
  `creatorid` INT UNSIGNED NOT NULL,
  FOREIGN KEY(creatorid)
    REFERENCES accounts (id)
    ON DELETE RESTRICT
);


CREATE TABLE `exam_questions` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `examid` INT UNSIGNED NOT NULL,
  `questionid` INT UNSIGNED NOT NULL,
  FOREIGN KEY (examid)
    REFERENCES exams (id)
    ON DELETE CASCADE,
  FOREIGN KEY (questionid)
    REFERENCES questions (id)
    ON DELETE RESTRICT
);
